# Generated by Django 3.1.2 on 2020-10-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Solar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(blank=True, max_length=60)),
                ('gridvoltage', models.CharField(blank=True, max_length=60)),
                ('gridfreq', models.CharField(blank=True, max_length=60)),
                ('outputvoltage', models.CharField(blank=True, max_length=60)),
                ('outputfreq', models.CharField(blank=True, max_length=60)),
                ('outputpowerapparent', models.CharField(blank=True, max_length=60)),
                ('outputpoweractive', models.CharField(blank=True, max_length=60)),
                ('loadpercent', models.CharField(blank=True, max_length=60)),
                ('busvoltage', models.CharField(blank=True, max_length=60)),
                ('batteryvoltage', models.CharField(blank=True, max_length=60)),
                ('batterycurrent', models.CharField(blank=True, max_length=60)),
                ('battery_capacity', models.CharField(blank=True, max_length=60)),
                ('temperature', models.CharField(blank=True, max_length=60)),
                ('solar_current', models.CharField(blank=True, max_length=60)),
                ('solar_voltage', models.CharField(blank=True, max_length=60)),
                ('battery_voltage_scc', models.CharField(blank=True, max_length=60)),
                ('battery_dis_current', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('warning', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
